Report/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(
        r'^$',
        'Report.views.index',
        name='index'),
    url(
        r'^history$',
        'Report.views.history',
        name='history'),
    url(
        r'^admin$',
        'Report.views.index_admin',
        name='index_admin'),
    url(
        r'^history_admin$',
        'Report.views.history_admin',
        name='history_admin'),
    url(
        r'^call_filter$',
        'Report.views.call_filter',
        name='call_filter'),
    url(
        r'^meet_filter$',
        'Report.views.meet_filter',
        name='meet_filter'),
    url(
        r'^approve_filter$',
        'Report.views.approve_filter',
        name='approve_filter'),
    url(
        r'^mining_filter$',
        'Report.views.mining_filter',
        name='mining_filter'),
    url(
        r'^export$',
        'Report.views.export',
        name='export'),
    url(
        r'^export_history$',
        'Report.views.history_export',
        name='export_history'),
    url(
        r'^export/file$',
        'Report.views.export_file',
        name='export_file'),
    url(
        r'^export/call_filter$',
        'Report.views.export_call_filter',
        name='export_call_filter'),
    url(
        r'^export/meet_filter$',
        'Report.views.export_meet_filter',
        name='export_meet_filter'),
    url(
        r'^export/approve_filter$',
        'Report.views.export_approve_filter',
        name='export_approve_filter'),
    url(
        r'^export/mining_filter$',
        'Report.views.export_mining_filter',
        name='export_mining_filter'),
    url(
        r'^get_all',
        'Report.views.get_all',
        name='get_all'),
    url(
        r'^get_full',
        'Report.views.get_full',
        name='get_full'),
    url(
        r'^get_one',
        'Report.views.get_one',
        name='get_one'),
    url(
        r'^add_item',
        'Report.views.add_item',
        name='add_item'),
    url(
        r'^edit_item',
        'Report.views.edit_item',
        name='edit_item'),
    url(
        r'^remove_item',
        'Report.views.remove_item',
        name='remove_item'),
)

User/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(
        r'^$',
        'User.views.index',
        name='index'),
    url(
        r'^quota$',
        'User.views.quota',
        name='quota'),
    url(
        r'^home$',
        'User.views.home',
        name='home'),
    url(
        r'^login$',
        'User.views.login',
        name='login'),
     url(
        r'^authenticate',
        'User.views.authenticate',
        name='authenticate'),
    url(
        r'^logout',
        'User.views.logout',
        name='logout'),
    url(
        r'^get_one',
        'User.views.get_one',
        name='get_one'),
    url(
        r'^edit_item',
        'User.views.edit_item'),
    url(
        r'^forgot_password$',
        'User.views.forgot_password',
        name='forgot_password'),
    url(
        r'^reset_password/(?P<user_id>\d+)/(?P<token>[\w-]+)$',
        'User.views.reset_password',
        name='reset_password'),
)

smereport/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    '',
    url(
        r'^$',
        'User.views.login',
        name='login'),
    url(
        r'^administrator/',
        include('Administrator.urls', namespace='administrator')),
    url(
        r'^admin$',
        'Administrator.views.login',
        name='admin'),
    url(
        r'^user/',
        include('User.urls', namespace='user')),
    url(
        r'^staff/',
        include('Staff.urls', namespace='staff')),
    url(
        r'^config/',
        include('Config.urls', namespace='config')),
    url(
        r'^tinhthanh/',
        include('Tinhthanh.urls', namespace='tinhthanh')),
    url(
        r'^category/',
        include('Category.urls', namespace='category')),
    url(
        r'^zone/',
        include('Zone.urls', namespace='zone')),
    url(
        r'^dropdown/',
        include('Dropdown.urls', namespace='dropdown')),
    url(
        r'^company/',
        include('Company.urls', namespace='company')),
    url(
        r'^report/',
        include('Report.urls', namespace='report')),
)

Report/views.py
# coding=utf8
# -*- coding: utf8 -*-
from django.shortcuts import render
from django.http import StreamingHttpResponse
from django.http import HttpResponse
from django.http import HttpResponseServerError
from django.http import Http404
from django.template import RequestContext
from django.core.context_processors import csrf
from Common.Tools import Tools
from Report.models import Report
from Report.models import ReportLog
from User.models import User
from Administrator.models import Administrator
from Company.models import Company
from Zone.models import Zone
from Category.models import Category
from Dropdown.models import Dropdown
from django.utils import timezone
from collections import OrderedDict
import copy
import xlsxwriter
import io
tools = Tools()
main_model = Report
report_log_model = ReportLog
user_model = User
admin_model = Administrator
company_model = Company
zone_model = Zone
dropdown_model = Dropdown
category_model = Category


def index(request):
    data = {}
    pk = request.session.get('USER_ID', None)
    user_item = user_model.objects.get_one({'pk': pk}, True)['data']
    list_company = company_model.objects.get_full({'sale': pk})['data']

    conditions = {
        'user': user_item.pk
    }

    sp_tiep_can_condition = tools.str_to_int(request.GET.get('sp_tiep_can', None))
    kq_cuoc_goi_condition = tools.str_to_int(request.GET.get('kq_cuoc_goi', None))
    kq_cuoc_gap_condition = tools.str_to_int(request.GET.get('kq_cuoc_gap', None))
    tt_khai_thac_condition = tools.str_to_int(request.GET.get('tt_khai_thac', None))

    if sp_tiep_can_condition is not None:
        conditions['sp_tiep_can'] = sp_tiep_can_condition
    if kq_cuoc_goi_condition is not None:
        conditions['kq_cuoc_goi'] = kq_cuoc_goi_condition
    if kq_cuoc_gap_condition is not None:
        conditions['kq_cuoc_gap'] = kq_cuoc_gap_condition
    if tt_khai_thac_condition is not None:
        conditions['tinh_trang_khai_thac'] = tt_khai_thac_condition

    ket_qua_cuoc_goi_cat = category_model.objects.get_one({'uid': 'ket-qua-cuoc-goi'}, True)['data']
    list_ket_qua_cuoc_goi = dropdown_model.objects.get_full({'category': ket_qua_cuoc_goi_cat})['data']

    ket_qua_cuoc_gap_cat = category_model.objects.get_one({'uid': 'kq-cuoc-gap'}, True)['data']
    list_ket_qua_cuoc_gap = dropdown_model.objects.get_full({'category': ket_qua_cuoc_gap_cat})['data']

    sp_tiep_can_cat = category_model.objects.get_one({'uid': 'sp-tiep-can'}, True)['data']
    list_sp_tiep_can = dropdown_model.objects.get_full({'category': sp_tiep_can_cat.pk})['data']

    tinh_trang_khai_thac_cat = category_model.objects.get_one({'uid': 'tinh-trang-khai-thac'}, True)['data']
    list_tinh_trang_khai_thac = dropdown_model.objects.get_full({'category': tinh_trang_khai_thac_cat.pk})['data']

    list_zone = zone_model.objects.get_full()['data']
    list_user = user_model.objects.get_full()['data']

    list_item = main_model.objects.get_all(conditions)['data']

    list_reported_company = []
    list_reported_company_object = main_model.objects.get_full({'user': user_item.pk}, ['cty'])['data']
    for item in list_reported_company_object:
        list_reported_company.append(int(item['cty']))

    data['js_vars'] = {}
    data['js_vars']['list_ket_qua_cuoc_goi'] = Tools.standardize_array(list_ket_qua_cuoc_goi)
    data['js_vars']['list_ket_qua_cuoc_gap'] = Tools.standardize_array(list_ket_qua_cuoc_gap)
    data['js_vars']['list_sp_tiep_can'] = Tools.standardize_array(list_sp_tiep_can)
    data['js_vars']['list_tinh_trang_khai_thac'] = Tools.standardize_array(list_tinh_trang_khai_thac)

    data['js_vars']['list_ket_qua_cuoc_goi_filter'] = Tools.standardize_array(list_ket_qua_cuoc_goi)
    data['js_vars']['list_ket_qua_cuoc_gap_filter'] = Tools.standardize_array(list_ket_qua_cuoc_gap)
    data['js_vars']['list_sp_tiep_can_filter'] = Tools.standardize_array(list_sp_tiep_can)
    data['js_vars']['list_tinh_trang_khai_thac_filter'] = Tools.standardize_array(list_tinh_trang_khai_thac)

    data['js_vars']['list_company'] = Tools.standardize_array(list_company)
    data['js_vars']['list_reported_company'] = list_reported_company
    data['js_vars']['list_zone'] = Tools.standardize_array(list_zone)
    data['js_vars']['list_user'] = Tools.standardize_array(list_user)
    data['js_vars']['list_item'] = Tools.standardize_array(list_item)

    data['js_vars']['conditions'] = conditions

    data['js_vars']['sp_tiep_can_condition'] = sp_tiep_can_condition
    data['js_vars']['kq_cuoc_goi_condition'] = kq_cuoc_goi_condition
    data['js_vars']['kq_cuoc_gap_condition'] = kq_cuoc_gap_condition
    data['js_vars']['tt_khai_thac_condition'] = tt_khai_thac_condition

    if len(data['js_vars']) != 0:
        data['js_vars'] = tools.encode_server_vars(data['js_vars'])
    else:
        data['js_vars'] = ''
    data['is_log'] = False
    data.update(csrf(request))
    return render(
        request,
        tools.get_app_name(__name__) + 'report.html',
        data,
        context_instance=RequestContext(request)
    )


def index_admin(request):
    data = {}
    conditions = {}
    pk = request.session.get('ADMIN_ID', None)
    admin_item = admin_model.objects.get_one({'pk': pk}, True)['data']

    sp_tiep_can_condition = tools.str_to_int(request.GET.get('sp_tiep_can', None))
    kq_cuoc_goi_condition = tools.str_to_int(request.GET.get('kq_cuoc_goi', None))
    kq_cuoc_gap_condition = tools.str_to_int(request.GET.get('kq_cuoc_gap', None))
    tt_khai_thac_condition = tools.str_to_int(request.GET.get('tt_khai_thac', None))

    if sp_tiep_can_condition is not None:
        conditions['sp_tiep_can'] = sp_tiep_can_condition
    if kq_cuoc_goi_condition is not None:
        conditions['kq_cuoc_goi'] = kq_cuoc_goi_condition
    if kq_cuoc_gap_condition is not None:
        conditions['kq_cuoc_gap'] = kq_cuoc_gap_condition
    if tt_khai_thac_condition is not None:
        conditions['tinh_trang_khai_thac'] = tt_khai_thac_condition

    ket_qua_cuoc_goi_cat = category_model.objects.get_one({'uid': 'ket-qua-cuoc-goi'}, True)['data']
    list_ket_qua_cuoc_goi = dropdown_model.objects.get_full({'category': ket_qua_cuoc_goi_cat})['data']

    ket_qua_cuoc_gap_cat = category_model.objects.get_one({'uid': 'kq-cuoc-gap'}, True)['data']
    list_ket_qua_cuoc_gap = dropdown_model.objects.get_full({'category': ket_qua_cuoc_gap_cat})['data']

    sp_tiep_can_cat = category_model.objects.get_one({'uid': 'sp-tiep-can'}, True)['data']
    list_sp_tiep_can = dropdown_model.objects.get_full({'category': sp_tiep_can_cat.pk})['data']

    tinh_trang_khai_thac_cat = category_model.objects.get_one({'uid': 'tinh-trang-khai-thac'}, True)['data']
    list_tinh_trang_khai_thac = dropdown_model.objects.get_full({'category': tinh_trang_khai_thac_cat.pk})['data']

    list_zone = zone_model.objects.get_full()['data']
    list_user = user_model.objects.get_full()['data']

    if admin_item.role == 'SADMIN' or admin_item.role == 'ADMIN':
        if not conditions:
            conditions = None
        list_item = main_model.objects.get_all(conditions)['data']
    else:
        zone_id = admin_item.zone.pk
        list_zone = zone_model.objects.get_full()['data']
        list_zone_pk = tools.get_list_hierarchy(zone_id, list_zone)
        list_zone_pk.append(zone_id)
        if not conditions:
            conditions = {
                'zone__in': list_zone_pk
            }
        else:
            conditions['zone__in'] = list_zone_pk
        list_item = main_model.objects.get_all(conditions)['data']
    data['js_vars'] = {}
    data['js_vars']['list_ket_qua_cuoc_goi'] = Tools.standardize_array(list_ket_qua_cuoc_goi)
    data['js_vars']['list_ket_qua_cuoc_gap'] = Tools.standardize_array(list_ket_qua_cuoc_gap)
    data['js_vars']['list_sp_tiep_can'] = Tools.standardize_array(list_sp_tiep_can)
    data['js_vars']['list_tinh_trang_khai_thac'] = Tools.standardize_array(list_tinh_trang_khai_thac)

    data['js_vars']['list_ket_qua_cuoc_goi_filter'] = Tools.standardize_array(list_ket_qua_cuoc_goi)
    data['js_vars']['list_ket_qua_cuoc_gap_filter'] = Tools.standardize_array(list_ket_qua_cuoc_gap)
    data['js_vars']['list_sp_tiep_can_filter'] = Tools.standardize_array(list_sp_tiep_can)
    data['js_vars']['list_tinh_trang_khai_thac_filter'] = Tools.standardize_array(list_tinh_trang_khai_thac)

    data['js_vars']['list_zone'] = Tools.standardize_array(list_zone)
    data['js_vars']['list_user'] = Tools.standardize_array(list_user)
    data['js_vars']['list_company'] = []
    data['js_vars']['list_item'] = Tools.standardize_array(list_item)

    data['js_vars']['conditions'] = conditions

    data['js_vars']['sp_tiep_can_condition'] = sp_tiep_can_condition
    data['js_vars']['kq_cuoc_goi_condition'] = kq_cuoc_goi_condition
    data['js_vars']['kq_cuoc_gap_condition'] = kq_cuoc_gap_condition
    data['js_vars']['tt_khai_thac_condition'] = tt_khai_thac_condition

    if len(data['js_vars']) != 0:
        data['js_vars'] = tools.encode_server_vars(data['js_vars'])
    else:
        data['js_vars'] = ''

    data['is_log'] = False
    data.update(csrf(request))
    return render(
        request,
        tools.get_app_name(__name__) + 'report_admin.html',
        data,
        context_instance=RequestContext(request)
    )


def history(request):
    data = {}
    pk = request.session.get('USER_ID', None)
    user_item = user_model.objects.get_one({'pk': pk}, True)['data']
    # list_company = company_model.objects.get_full({'sale': pk})['data']

    conditions = {
        'user': user_item.pk
    }

    sp_tiep_can_condition = tools.str_to_int(request.GET.get('sp_tiep_can', None))
    kq_cuoc_goi_condition = tools.str_to_int(request.GET.get('kq_cuoc_goi', None))
    kq_cuoc_gap_condition = tools.str_to_int(request.GET.get('kq_cuoc_gap', None))
    tt_khai_thac_condition = tools.str_to_int(request.GET.get('tt_khai_thac', None))

    if sp_tiep_can_condition is not None:

Report/templates/Report/report.html
{% extends 'back/base_user.html' %}
{% load static %}
{% block title %}Report{% endblock %}
{% block content %}

    <div data-ng-controller="ClientReport" ng-init="init(false)">
        {% if is_log %}
            <form class="five column stackable ui grid" method="get" action="./history">
        {% else %}
            <form class="five column stackable ui grid" method="get" action="./">
        {% endif %}

            <input type="hidden" id="sp_tiep_can" name="sp_tiep_can"/>
            <input type="hidden" id="kq_cuoc_goi" name="kq_cuoc_goi"/>
            <input type="hidden" id="kq_cuoc_gap" name="kq_cuoc_gap"/>
            <input type="hidden" id="tt_khai_thac" name="tt_khai_thac"/>

            <div class="column">
                <select id="select-sp_tiep_can_filter"></select>
            </div>
            <div class="column">
                <select id="select-kq_cuoc_goi_filter"></select>
            </div>
            <div class="column">
                <select id="select-kq_cuoc_gap_filter"></select>
            </div>

            <div class="column">
                <select id="select-tinh_trang_khai_thac_filter"></select>
            </div>
            <div class="column">
                <button class="ui button">
                    <i class="filter icon"></i>
                    Filter
                </button>
            </div>
        </form>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 30px;cursor: pointer" data-ng-click="selectAllCheckBox()">
                        <i class="checkmark icon" style="font-size: 20px"></i>
                    </th>
                    <th>TM</th>
                    <th>Hub</th>
                    <th>MST</th>
                    <th>Công ty</th>
                    <th>SP tiếp cận</th>
                    <th>KQ cuộc gọi</th>
                    <th>KQ cuộc gặp</th>
                    <th>TT khai thác</th>
                    <th>Commit status</th>
                    <th colspan="3" style="text-align: center">
                        <b style="cursor: pointer" data-ng-click="openFormEdit()" ng-show="model.ref.list_company">
                            <span class="glyphicon glyphicon-plus-sign"></span>
                            Add new &nbsp;&nbsp;
                        </b>
                    </th>
                </tr>
            </thead>
            
            <tbody>
                <tr>
                    <td>
                        <i class="remove icon" data-ng-show="model.vars.listItemId" style="font-size: 20px" data-ng-click="openFormRemove(model.vars.listItemId)"></i>
                    </td>
                    <td colspan="12">
                        <div class="ui fluid input">
                            <input type="text" class="form-control" data-ng-model="model.vars.inputFilter" autofocus placeholder="Search..." />
                        </div>
                    </td>
                </tr>
                <tr data-ng-repeat="item in model.vars.listItem">
                    <td><input type="checkbox" class="selectCheckBox" data="{$ item.id $}" data-ng-click="selectCheckBox()" /></td>
                    <td>{$ item.user | mapTitle : model.ref.list_user_ref $}</td>
                    <td>{$ item.zone_id | mapTitle : model.ref.list_zone_ref $}</td>
                    <td>{$ item.cty_mst $}</td>
                    <td>{$ item.cty_name $}</td>
                    <td>{$ item.sp_tiep_can | mapTitle : model.ref.list_sp_tiep_can_ref $}</td>
                    <td>{$ item.kq_cuoc_goi | mapTitle : model.ref.list_ket_qua_cuoc_goi_ref $}</td>
                    <td>{$ item.kq_cuoc_gap | mapTitle : model.ref.list_ket_qua_cuoc_gap_ref $}</td>
                    <td>{$ item.tinh_trang_khai_thac | mapTitle : model.ref.list_tinh_trang_khai_thac_ref $}</td>
                    <td><span ng-bind-html='item.commit | toString : other'></span></td>

                    <td class="action-icon" data-ng-click="openFormView(item.id)"><i class="search icon" style="font-size: 20px"></i></td>
                    <td class="action-icon" data-ng-click="openFormEdit(item.id)"><i class="pencil icon" style="font-size: 20px"></i></td>
                    <td class="action-icon" data-ng-click="openFormRemove(item.id)"><i class="remove icon" style="font-size: 20px"></i></td>
                </tr>
                
            </tbody>
            
            <tfoot>
                <tr>
                    <th style="cursor: pointer">
                        <i class="remove icon" data-ng-show="model.vars.listItemId" style="font-size: 20px" data-ng-click="openFormRemove(model.vars.listItemId)"></i>
                    </th>
                    <th colspan="11">
                        &nbsp;
                    </th>
                </tr>
            </tfoot>
            
        </table>
        {% include 'Report/report_modal.html' %}
        {% include 'Report/report_modal_view.html' %}
    </div>

{% endblock %}

Report/templates/Report/report_export.html
{% extends extends_template %}
{% load static %}
{% block title %}Export Report{% endblock %}
{% block content %}
    <script type="text/javascript">
        $(function(){
            var current_date = new Date();
            var year_str = current_date.getFullYear().toString();
            var month_str = "";
            var day_str = "";
            if(current_date.getMonth() < 10 ){
                month_str = "0" + (current_date.getMonth() + 1).toString();
            }else{
                month_str = (current_date.getMonth() + 1).toString();
            }
            if(current_date.getDate() < 10 ){
                day_str = "0" + current_date.getDate().toString();
            }else{
                day_str = current_date.getDate().toString();
            }

            var date_str = year_str + "-" + month_str + "-" + day_str;
            var dateOption = {
                timepicker: false,
                closeOnDateSelect: true,
                mask: true,
                format: 'Y-m-d'
            };
            var basic_date = $('#basic_date')
            basic_date.datetimepicker(dateOption);
            basic_date.val(date_str);

            var start_date = $('#start_date')
            start_date.datetimepicker(dateOption);
            start_date.val(date_str);

            var end_date = $('#end_date')
            end_date.datetimepicker(dateOption);
            end_date.val(date_str);
        });
    </script>
    <div>
        <h2 style="margin:0;line-height: 1">Export report</h2>
        <hr/>
        <form action="{% url 'report:export_file' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="history" value="0" />
            <div class="ui input">
                <input type="text" id="basic_date" name="basic_date" placeholder="Date...">
            </div>
            <br/>
            <br/>
            <div class="ui form">
                <div class="grouped inline fields">
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" id="day_range" name="basic_range" value="day" checked="">
                            <label for="day_range">Day</label>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" id="week_range" name="basic_range" value="week">
                            <label for="week_range">Week</label>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" id="month_range" name="basic_range" value="month">
                            <label for="month_range">Month</label>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" id="year_range" name="basic_range" value="year">
                            <label for="year_range">Year</label>
                        </div>
                    </div>
                </div>
            </div>
            <br/>
            <button class="ui secondary button">
                <i class="download icon"></i>
                Export
            </button>
            <br/>
            <br/>
        </form>

        <h2 style="margin:0;line-height: 1">Custom export</h2>
        <hr/>
        <form action="{% url 'report:export_file' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="history" value="0" />
            <table>
                <tr>
                    <td>From &nbsp;&nbsp;</td>
                    <td>
                        <div class="ui input">
                            <input type="text" id="start_date" name="start_date" placeholder="Start Date...">
                        </div>
                    </td>
                    <td>&nbsp;&nbsp; To &nbsp;&nbsp;</td>
                    <td>
                        <div class="ui input">
                            <input type="text" id="end_date" name="end_date" placeholder="End Date...">
                        </div>
                    </td>
                </tr>
            </table>
            <br/>
            <button class="ui secondary button">
                <i class="download icon"></i>
                Export
            </button>
        </form>
    </div>

{% endblock %}

Report/templates/Report/report_history_export.html
{% extends extends_template %}
{% load static %}
{% block title %}Export Report{% endblock %}
{% block content %}
    <script type="text/javascript">
        $(function(){
            var current_date = new Date();
            var year_str = current_date.getFullYear().toString();
            var month_str = "";
            var day_str = "";
            if(current_date.getMonth() < 10 ){
                month_str = "0" + (current_date.getMonth() + 1).toString();
            }else{
                month_str = (current_date.getMonth() + 1).toString();
            }
            if(current_date.getDate() < 10 ){
                day_str = "0" + current_date.getDate().toString();
            }else{
                day_str = current_date.getDate().toString();
            }

            var date_str = year_str + "-" + month_str + "-" + day_str;
            var dateOption = {
                timepicker: false,
                closeOnDateSelect: true,
                mask: true,
                format: 'Y-m-d'
            };
            var basic_date = $('#basic_date')
            basic_date.datetimepicker(dateOption);
            basic_date.val(date_str);

            var start_date = $('#start_date')
            start_date.datetimepicker(dateOption);
            start_date.val(date_str);

            var end_date = $('#end_date')
            end_date.datetimepicker(dateOption);
            end_date.val(date_str);
        });
    </script>
    <div>
        <h2 style="margin:0;line-height: 1">Export report</h2>
        <hr/>
        <form action="{% url 'report:export_file' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="history" value="1" />
            <div class="ui input">
                <input type="text" id="basic_date" name="basic_date" placeholder="Date...">
            </div>
            <br/>
            <br/>
            <div class="ui form">
                <div class="grouped inline fields">
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" id="day_range" name="basic_range" value="day" checked="">
                            <label for="day_range">Day</label>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" id="week_range" name="basic_range" value="week">
                            <label for="week_range">Week</label>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" id="month_range" name="basic_range" value="month">
                            <label for="month_range">Month</label>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" id="year_range" name="basic_range" value="year">
                            <label for="year_range">Year</label>
                        </div>
                    </div>
                </div>
            </div>
            <br/>
            <button class="ui secondary button">
                <i class="download icon"></i>
                Export
            </button>
            <br/>
            <br/>
        </form>

        <h2 style="margin:0;line-height: 1">Custom export</h2>
        <hr/>
        <form action="{% url 'report:export_file' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="history" value="1" />
            <table>
                <tr>
                    <td>From &nbsp;&nbsp;</td>
                    <td>
                        <div class="ui input">
                            <input type="text" id="start_date" name="start_date" placeholder="Start Date...">
                        </div>
                    </td>
                    <td>&nbsp;&nbsp; To &nbsp;&nbsp;</td>
                    <td>
                        <div class="ui input">
                            <input type="text" id="end_date" name="end_date" placeholder="End Date...">
                        </div>
                    </td>
                </tr>
            </table>
            <br/>
            <button class="ui secondary button">
                <i class="download icon"></i>
                Export
            </button>
        </form>
    </div>

{% endblock %}