User/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(
        r'^$',
        'User.views.index',
        name='index'),
    url(
        r'^quota$',
        'User.views.quota',
        name='quota'),
    url(
        r'^home$',
        'User.views.home',
        name='home'),
    url(
        r'^login$',
        'User.views.login',
        name='login'),
     url(
        r'^authenticate',
        'User.views.authenticate',
        name='authenticate'),
    url(
        r'^logout',
        'User.views.logout',
        name='logout'),
    url(
        r'^get_one',
        'User.views.get_one',
        name='get_one'),
    url(
        r'^edit_item',
        'User.views.edit_item'),
    url(
        r'^forgot_password$',
        'User.views.forgot_password',
        name='forgot_password'),
    url(
        r'^reset_password/(?P<user_id>\d+)/(?P<token>[\w-]+)$',
        'User.views.reset_password',
        name='reset_password'),
)

smereport/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    '',
    url(
        r'^$',
        'User.views.login',
        name='login'),
    url(
        r'^administrator/',
        include('Administrator.urls', namespace='administrator')),
    url(
        r'^admin$',
        'Administrator.views.login',
        name='admin'),
    url(
        r'^user/',
        include('User.urls', namespace='user')),
    url(
        r'^staff/',
        include('Staff.urls', namespace='staff')),
    url(
        r'^config/',
        include('Config.urls', namespace='config')),
    url(
        r'^tinhthanh/',
        include('Tinhthanh.urls', namespace='tinhthanh')),
    url(
        r'^category/',
        include('Category.urls', namespace='category')),
    url(
        r'^zone/',
        include('Zone.urls', namespace='zone')),
    url(
        r'^dropdown/',
        include('Dropdown.urls', namespace='dropdown')),
    url(
        r'^company/',
        include('Company.urls', namespace='company')),
    url(
        r'^report/',
        include('Report.urls', namespace='report')),
)

Common/models.py
from django.db import models

# Create your models here.

Common/views.py
# Create your views here.

Common/templates/back/base_admin.html
{% load static %}
{% load category_sub_items %}
<!DOCTYPE html>

<html lang="vi">
	<head>
        <title data-base-url="{{ BASE_URL }}" data-static-url="{{ STATIC_URL }}" data-media-url="{{ MEDIA_URL }}">
            {% block title %}{% endblock %}
        </title>
        {% include 'back/header_ref.html' %}
		<style type="text/css">
			#spinner {
				position: fixed;
				left: 0px;
				top: 0px;
				width: 100%;
				height: 100%;
				z-index: 99999;
				/*
				opacity: 0.8;
				*/
				background: url("{{ STATIC_URL }}img/loading-line.gif") 50% 50% no-repeat white;
			}
		</style>
    </head>
		
    <body data-ng-app="App" class="container"><div id="spinner"></div>
		<div id="waiting-heading">
			<img src="{% static 'img/loading-line.gif' %}" style="margin-top: 10px" />
		</div>
		<div id="wrapper" class="remodal-bg">
			<input type="hidden" id="js-vars" value="{{ js_vars }}" />
			
			<div class="ui grid main-container">
				<div class="two column row hf-background">
					<div class="four wide column" style="padding-top: 4px">
						<a href="{% url 'administrator:index' %}" style="color:white">
							<span class="main-logo">SMER</span>
						</a>
					</div>
					<div class="twelve wide column" style="padding-top: 5px">
						<div style="margin: 6px;text-align: right">
							Hello <span><b>{{ ADMIN_FULLNAME }}</b></span>&nbsp;
							<a href="{% url 'administrator:logout' %}" style="color:white; text-decoration: none">
								<i class="ui off icon"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
			
			<div class="ui grid stackable main-container">
				<div class="two column row">
					<div class="three wide column" style="padding-right: 0">
						<div class="ui fluid vertical menu">
							<a class="item" href="{% url 'administrator:home' %}" id='administrator-home'>
								Home
							</a>
							{% if ADMIN_ROLE == 'SADMIN' or ADMIN_ROLE == 'ADMIN' %}
                            <a class="item" href="{% url 'administrator:index' %}" id='administrator-index'>
								Admin
							</a>
                            {% endif %}

                            {% if ADMIN_ROLE == 'SADMIN' or ADMIN_ROLE == 'ADMIN' %}
							<a class="item" href="{% url 'staff:index' %}" id='staff-index'>
								User
							</a>
                            {% endif %}

                            {% if ADMIN_ROLE == 'SADMIN' %}
							<a class="item" href="{% url 'config:index' %}" id='config-index'>
								Config
							</a>
                            <a class="item" href="{% url 'tinhthanh:index' %}" id='tinhthanh-index'>
								Tỉnh thành
							</a>
							<a class="item" href="{% url 'category:index' %}" id='category-index'>
								Category
							</a>
                            {% endif %}

                            {% if ADMIN_ROLE == 'SADMIN' or ADMIN_ROLE == 'ADMIN' %}
                            <a class="item" href="{% url 'company:index' %}" id='company-index'>
								Company
							</a>
                            {% endif %}

                            <a class="item" href="{% url 'administrator:quota' %}" id='administrator-quota'>
								Quota
							</a>

                            <a class="item" href="{% url 'report:index_admin' %}" id='report-index_admin'>
								Report
							</a>
                            <a class="item" href="{% url 'report:history_admin' %}" id='report-history_admin'>
								Report history
							</a>
                        </div>

                        <div class="ui fluid vertical menu">
                            <a class="item" href="{% url 'report:call_filter' %}" id='report-call_filter'>
								Export call report
							</a>

							<a class="item" href="{% url 'report:meet_filter' %}" id='report-meet_filter'>
								Export meet report
							</a>

							<a class="item" href="{% url 'report:approve_filter' %}" id='report-approve_filter'>
								Export approve report
							</a>

                            <a class="item" href="{% url 'report:mining_filter' %}" id='report-mining_filter'>
								Export mining report
							</a>

                            <a class="item" href="{% url 'report:export' %}" id='report-export'>
								Export basic report
							</a>
                            <a class="item" href="{% url 'report:export_history' %}" id='report-export_history'>
								Export basic report log
							</a>
						</div>

                        {% if ADMIN_ROLE == 'SADMIN' %}
                            {% category_sub_items 'zone' %}

                            {% category_sub_items 'dropdown' %}
						{% endif %}
						{#% category_zone_items 'dropdown' %#}
					</div>
					<div class="thirteen wide column">
						{% block content %}{% endblock %}
					</div>
				</div>
			</div>
			
			<br/>
			<br/>
			
			<div id="main-footer" class="hf-background main-container" style="text-align: right">
				<div style="position: relative; padding-top: 13px; padding-right: 30px">
					<span>
						©2014 XIVILA
					</span>
				</div>
			</div>
		</div>
        {% include 'back/footer_ref.html' %}
    </body>
</html>

Common/templates/back/base_user.html
{% load static %}
{% load category_sub_items %}
<!DOCTYPE html>

<html lang="vi">
	<head>
        <title data-base-url="{{ BASE_URL }}" data-static-url="{{ STATIC_URL }}" data-media-url="{{ MEDIA_URL }}">
            {% block title %}{% endblock %}
        </title>
        {% include 'back/header_ref.html' %}
		<style type="text/css">
			#spinner {
				position: fixed;
				left: 0px;
				top: 0px;
				width: 100%;
				height: 100%;
				z-index: 99999;
				/*
				opacity: 0.8;
				*/
				background: url("{{ STATIC_URL }}img/loading-line.gif") 50% 50% no-repeat white;
			}
		</style>
    </head>
		
    <body data-ng-app="App" class="container"><div id="spinner"></div>
		<div id="waiting-heading">
			<img src="{% static 'img/loading-line.gif' %}" style="margin-top: 10px" />
		</div>
		<div id="wrapper" class="remodal-bg">
			<input type="hidden" id="js-vars" value="{{ js_vars }}" />
			
			<div class="ui grid main-container">
				<div class="two column row hf-background">
					<div class="four wide column" style="padding-top: 4px">
						<a href="{% url 'user:index' %}" style="color:white">
							<span class="main-logo">SMER</span>
						</a>
					</div>
					<div class="twelve wide column" style="padding-top: 5px">
						<div style="margin: 6px;text-align: right">
							Hello <span><b>{{ USER_FULLNAME }}</b></span>&nbsp;
							<a href="{% url 'user:logout' %}" style="color:white; text-decoration: none">
								<i class="ui off icon"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
			
			<div class="ui grid stackable main-container">
				<div class="two column row">
					<div class="three wide column" style="padding-right: 0">
						<div class="ui fluid vertical menu">
							<a class="item" href="{% url 'user:home' %}" id='user-home'>
								Home
							</a>
                            <a class="item" href="{% url 'user:quota' %}" id='user-quota'>
								Quota
							</a>
                            <a class="item" href="{% url 'report:index' %}" id='report-index'>
								Report
							</a>
                            <a class="item" href="{% url 'report:history' %}" id='report-history'>
								Report history
							</a>
                        </div>

                        <div class="ui fluid vertical menu">
                            <a class="item" href="{% url 'report:call_filter' %}" id='report-call_filter'>
								Export call report
							</a>

							<a class="item" href="{% url 'report:meet_filter' %}" id='report-meet_filter'>
								Export meet report
							</a>

							<a class="item" href="{% url 'report:approve_filter' %}" id='report-approve_filter'>
								Export approve report
							</a>

                            <a class="item" href="{% url 'report:mining_filter' %}" id='report-mining_filter'>
								Export mining report
							</a>

                            <a class="item" href="{% url 'report:export' %}" id='report-export'>
								Export basic report
							</a>
                            <a class="item" href="{% url 'report:export_history' %}" id='report-export_history'>
								Export basic report log
							</a>
						</div>


					</div>
					<div class="thirteen wide column">
						{% block content %}{% endblock %}
					</div>
				</div>
			</div>
			
			<br/>
			<br/>
			
			<div id="main-footer" class="hf-background main-container" style="text-align: right">
				<div style="position: relative; padding-top: 13px; padding-right: 30px">
					<span>
						©2014 XIVILA
					</span>
				</div>
			</div>
		</div>
        {% include 'back/footer_ref.html' %}
    </body>
</html>

Common/templates/back/category_sub_items.html
{% if list_side_item %}
<div class="ui fluid vertical menu">
    {% for item in list_side_item %}
    <a class="item" href="{% url template_name category_id=item.id %}" id='{{ cattype }}-index-{{item.id}}'>
        {{ item.title }}
    </a>
    {% endfor %}
</div>
{% endif %}

Common/templates/back/footer_ref.html
{% load static %}
{% load compress %}

<script type="text/javascript" src="{% static 'libraries/jquery/responsive-tab/js/easyResponsiveTabs.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/jquery/bootstrap-filestyle.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/jquery/jquery.mousewheel.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/jquery/jquery.cookie.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/jquery/remodal/jquery.remodal.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/jquery/jstree/jstree.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/jquery/datetimepicker/jquery.datetimepicker.js' %}"></script>



<script type="text/javascript" src="{% static 'libraries/semantic/packaged/javascript/semantic.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/semantic/minified/modules/modal.min.js' %}"></script>

<script type="text/javascript" src="{% static 'libraries/bootstrap/js/bootstrap.min.js'%}"></script>

<script type="text/javascript" src="{% static 'libraries/ssm/ssm.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/selectize/js/standalone/selectize.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/tinymce/tinymce.min.js' %}"></script>



<script type="text/javascript" src="{% static 'libraries/angular/angular.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/angular/angular-sanitize.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/angular/tinymce/tinymce.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/angular/sortable/sortable.js' %}"></script>

{% compress js %}
<script type="text/javascript" src="{% static 'app/construct.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/common/models/common-assess.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-admin-login/models/client-admin-login-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-admin-login/client-admin-login.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-staff/models/client-staff-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-staff/client-staff.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-user/models/client-user-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-user/client-user.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-user-login/models/client-user-login-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-user-login/client-user-login.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-admin/models/client-admin-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-admin/client-admin.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-config/models/client-config-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-config/client-config.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-tinhthanh/models/client-tinhthanh-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-tinhthanh/client-tinhthanh.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-report/models/client-report-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-report/client-report.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-report/client-report-export.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-category/models/client-category-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-category/client-category.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-company/models/client-company-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-company/client-company.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-company/client-company-exchange.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-zone/models/client-zone-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-zone/client-zone.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-template/models/client-template-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-template/client-template.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-dropdown/models/client-dropdown-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-dropdown/client-dropdown.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-dropdown-item/models/client-dropdown-item-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-dropdown-item/client-dropdown-item.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-cv/models/client-cv-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-cv/client-cv.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-cv/client-cv-list.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-basic-info/models/client-cv-basic-info-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-basic-info/client-cv-basic-info.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-awards/models/client-cv-awards-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-awards/client-cv-awards.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-languages/models/client-cv-languages-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-languages/client-cv-languages.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-educations/models/client-cv-educations-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-educations/client-cv-educations.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-projects/models/client-cv-projects-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-projects/client-cv-projects.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-working-history/models/client-cv-working-history-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-working-history/client-cv-working-history.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-skills/models/client-cv-skills-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-skills/client-cv-skills.js' %}"></script>

<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-export/models/client-cv-export-model.js' %}"></script>
<script type="text/javascript" src="{% static 'app/modules/client-cv-part/cv-export/client-cv-export.js' %}"></script>
{% endcompress %}

Common/templates/back/header_ref.html
{% load static %}
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel='stylesheet' href="{% static 'libraries/semantic/packaged/css/semantic.min.css' %}" />
<link rel='stylesheet' href="{% static 'libraries/selectize/css/selectize.css' %}" />
<link rel='stylesheet' href="{% static 'libraries/angular/ng-table/css/ng-table.min.css' %}" />
<link rel='stylesheet' href="{% static 'libraries/jquery/remodal/jquery.remodal.css' %}" />
<link rel='stylesheet' href="{% static 'libraries/jquery/responsive-tab/css/easy-responsive-tabs.css' %}" />

<link rel='stylesheet' href="{% static 'libraries/bootstrap/css/bootstrap.min.css' %}" />

<link rel='stylesheet' href="{% static 'libraries/jquery/jstree/themes/default/style.min.css' %}" />
<link rel='stylesheet' href="{% static 'libraries/jquery/datetimepicker/jquery.datetimepicker.css' %}" />

<link rel='stylesheet' href="{% static 'css/back.css' %}" />
<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png?v=2' %}"/>
<script type="text/javascript" src="{% static 'libraries/jquery/jquery-2.1.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/jquery/jquery-ui.min.js' %}"></script>

<script type="text/javascript">
    $(function(){
        $("#spinner").fadeOut("slow");
        var currentMenu = "#" + "{{ CURRENT_MENU }}";
        var currentMenuSide = "#" + "{{ CURRENT_MENU }}-side";
        $(currentMenu).addClass('active');
        $(currentMenuSide).addClass('active');

        $('img').bind('error', function (e) {
            $(this).attr('src', '{{ STATIC_URL }}img/default-thumbnail.jpg');
        });
    });
</script>

Common/templates/back/home.html
{% load static %}
<!DOCTYPE html>
<html lang="vi">
	<head>
		<meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title data-base-url="{{ BASE_URL }}" data-static-url="{{ STATIC_URL }}" data-media-url="{{ MEDIA_URL }}">
            {% block title %}{% endblock %}
        </title>

        {% include 'back/header_ref.html' %}

        <link rel='stylesheet' href="{% static 'css/back.css' %}" />
        <link rel='stylesheet' href="{% static 'libraries/angular/ng-table/css/ng-table.min.css' %}" />

    </head>

    <body data-ng-app="App" class="container">
        <div id="waiting-heading">
            <img src="{% static 'img/loading-line.gif' %}" style="margin-top: 10px" />
        </div>
        <input type="hidden" id="js-vars" value="{{ js_vars }}" />
        <div class="row">
            <div class="col-md-12 hf-background">
                <div class="row">
                    <div class="col-md-4">
                        <a href="{% url 'user:index' %}" style="color:white">
                            <span class="main-logo">XIVILA</span>
                        </a>
                    </div>

                    <div class="col-md-8" data-ng-controller='ClientUserLogin'>
                        <form class="form-inline" role="form" data-ng-submit='submitFormLogin()' method="post" accept-charset="utf-8">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="sr-only" for="userEmail">Email address</label>
                                <input type="email" class="form-control" id="userEmail" data-ng-model='email' autofocus required placeholder="Email...">
                            </div>

                            <div class="form-group">
                                <label class="sr-only" for="userPassword">Password</label>
                                <input type="password" class="form-control" id="userPassword" data-ng-model='password' required placeholder="Password...">
                            </div>

                            <button type="submit" class="btn btn-info">Sign in</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>

        <br/>

        <div class="row">
            <div class="col-md-12">
                {% block content %}{% endblock %}
            </div>
        </div>

        <div class="row hf-background">
            <div class="col-md-12" style="margin-top: 8px">
                ©2014 XIVILA
            </div>
        </div>

        {% include 'back/footer_ref.html' %}

    </body>
</html>

Common/templates/back/login.html
{% load static %}
<!DOCTYPE html>
<html lang="vi">
	<head>
		<title data-base-url="{{ BASE_URL }}" data-static-url="{{ STATIC_URL }}" data-media-url="{{ MEDIA_URL }}">
            {% block title %}{% endblock %}
        </title>
        {% include 'back/header_ref.html' %}
		<style type="text/css">
			#spinner {
				position: fixed;
				left: 0px;
				top: 0px;
				width: 100%;
				height: 100%;
				z-index: 99999;
				/*
				opacity: 0.8;
				*/
				background: url("{{ STATIC_URL }}img/loading-line.gif") 50% 50% no-repeat white;
			}
		</style>
    </head>

    <body data-ng-app="App" class="container"><div id="spinner"></div>
		<div id="waiting-heading">
			<img src="{% static 'img/loading-line.gif' %}" style="margin-top: 10px" />
		</div>
        {% block content %}{% endblock %}
		
        {% include 'back/footer_ref.html' %}
    </body>
</html>